CREATE TABLE IF NOT EXISTS orven_store (
 id INTEGER PRIMARY KEY CHECK (id = 1),
 payload JSONB NOT NULL,
 revision INTEGER NOT NULL DEFAULT 1,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS orven_login_limits (
 key TEXT PRIMARY KEY,
 attempts INTEGER NOT NULL DEFAULT 0,
 window_start TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
