function validate(body){const fail=m=>{const e=Error(m);e.status=400;throw e};const str=(v,max)=>typeof v==='string'&&v.length<=max;const image=v=>str(v,1500)&&(v.startsWith('/assets/images/')&&!v.includes('..')||/^https:\/\//.test(v));
 if(!body||!Array.isArray(body.products)||body.products.length>200||!body.settings||!Number.isInteger(body.revision)||body.revision<0)fail('Məlumat formatı yanlışdır.');const s=body.settings;
 for(const k of ['heroTitle','heroAccent'])if(!str(s[k],100)||!s[k].trim())fail('Başlıqlar boş ola bilməz və maksimum 100 simvol olmalıdır.');
 for(const k of ['heroDescription','about','footerText'])if(!str(s[k],5000))fail('Mətnlər maksimum 5000 simvol olmalıdır.');
 if(!Array.isArray(s.heroImages)||s.heroImages.length<1||s.heroImages.length>6||!s.heroImages.every(image))fail('1–6 etibarlı foto ünvanı daxil edin.');
 for(const [k,domain] of [['instagram','instagram.com'],['tiktok','tiktok.com']]){if(!str(s[k],1500))fail('Sosial link yanlışdır.');if(s[k]){let u;try{u=new URL(s[k])}catch{fail('Sosial link yanlışdır.')}if(u.protocol!=='https:'||!(u.hostname===domain||u.hostname.endsWith('.'+domain)))fail('Sosial link domeni uyğun deyil.')}}
 if(!str(s.whatsapp,20)||(s.whatsapp&&!/^\+?\d{7,15}$/.test(s.whatsapp)))fail('WhatsApp nömrəsini ölkə kodu ilə, boşluqsuz daxil edin.');
 if(!Number.isFinite(s.animationSpeed)||s.animationSpeed<.5||s.animationSpeed>2||typeof s.animationEnabled!=='boolean')fail('Animasiya parametrləri yanlışdır.');
 const ids=new Set();for(const p of body.products){if(!str(p.id,80)||!p.id||ids.has(p.id)||!str(p.name,120)||!p.name.trim()||!['tshirts','hoodies','pants'].includes(p.category)||!image(p.image)||!str(p.color,100)||!str(p.description,5000)||!str(p.price,20)||(p.price&&!/^\d+(\.\d{1,2})?$/.test(p.price))||!Array.isArray(p.sizes)||p.sizes.length<1||p.sizes.length>6||!p.sizes.every(v=>['XS','S','M','L','XL','XXL'].includes(v))||typeof p.active!=='boolean'||typeof p.sample!=='boolean')fail('Məhsul məlumatlarını yoxlayın.');ids.add(p.id)}
 return {settings:Object.fromEntries(['heroTitle','heroAccent','heroDescription','heroImages','instagram','tiktok','whatsapp','about','footerText','animationSpeed','animationEnabled'].map(k=>[k,s[k]])),products:body.products.map(p=>Object.fromEntries(['id','name','category','color','image','price','sizes','description','active','sample'].map(k=>[k,p[k]])))}
}
module.exports={validate};
